/**
 * Animals data for memory game usage
 * Images origin: https://www.pexels.com/
 * License: Free to use, Creative Commons Zero (CC0) license.
 */
const animals = [
  {
    id: 0,
    enName: 'squirrel',
    imagePath: './animal_images/squirrel.jpg',
    textPath: './animal_names/squirrel.jpg',
    difficulty: 0,
  },
  {
    id: 1,
    enName: 'elephant',
    imagePath: './animal_images/elephant.jpg',
    textPath: './animal_names/elephant.jpg',
    difficulty: 0,
  },
  {
    id: 2,
    enName: 'lion',
    imagePath: './animal_images/lion.jpg',
    textPath: './animal_names/lion.jpg',
    difficulty: 0,
  },
  {
    id: 3,
    enName: 'tiger',
    imagePath: './animal_images/tiger.jpg',
    textPath: './animal_names/tiger.jpg',
    difficulty: 0,
  },
  {
    id: 4,
    enName: 'giraffe',
    imagePath: './animal_images/giraffe.jpg',
    textPath: './animal_names/giraffe.jpg',
    difficulty: 0,
  },
  {
    id: 5,
    enName: 'chameleon',
    imagePath: './animal_images/chameleon.jpg',
    textPath: './animal_names/chameleon.jpg',
    difficulty: 1,
  },
  {
    id: 6,
    enName: 'dog',
    imagePath: './animal_images/dog.jpg',
    textPath: './animal_names/dog.jpg',
    difficulty: 0,
  },
  {
    id: 7,
    enName: 'cat',
    imagePath: './animal_images/cat.jpg',
    textPath: './animal_names/cat.jpg',
    difficulty: 0,
  },
  {
    id: 8,
    enName: 'deer',
    imagePath: './animal_images/deer.jpg',
    textPath: './animal_names/deer.jpg',
    difficulty: 0,
  },
  {
    id: 9,
    enName: 'fox',
    imagePath: './animal_images/fox.jpg',
    textPath: './animal_names/fox.jpg',
    difficulty: 0,
  },
  {
    id: 10,
    enName: 'horse',
    imagePath: './animal_images/horse.jpg',
    textPath: './animal_names/horse.jpg',
    difficulty: 0,
  },
  {
    id: 11,
    enName: 'penguin',
    imagePath: './animal_images/penguin.jpg',
    textPath: './animal_names/penguin.jpg',
    difficulty: 0,
  },
  {
    id: 12,
    enName: 'toucan',
    imagePath: './animal_images/toucan.jpg',
    textPath: './animal_names/toucan.jpg',
    difficulty: 1,
  },
  {
    id: 13,
    enName: 'hedgehog',
    imagePath: './animal_images/hedgehog.jpg',
    textPath: './animal_names/hedgehog.jpg',
    difficulty: 2,
  },
  {
    id: 14,
    enName: 'fish',
    imagePath: './animal_images/fish.jpg',
    textPath: './animal_names/fish.jpg',
    difficulty: 0,
  },
  {
    id: 15,
    enName: 'owl',
    imagePath: './animal_images/owl.jpg',
    textPath: './animal_names/owl.jpg',
    difficulty: 1,
  },
  {
    id: 16,
    enName: 'snake',
    imagePath: './animal_images/snake.jpg',
    textPath: './animal_names/snake.jpg',
    difficulty: 0,
  },
  {
    id: 17,
    enName: 'frog',
    imagePath: './animal_images/frog.jpg',
    textPath: './animal_names/frog.jpg',
    difficulty: 0,
  },
  {
    id: 18,
    enName: 'panda',
    imagePath: './animal_images/panda.jpg',
    textPath: './animal_names/panda.jpg',
    difficulty: 0,
  },
  {
    id: 19,
    enName: 'parrot',
    imagePath: './animal_images/parrot.jpg',
    textPath: './animal_names/parrot.jpg',
    difficulty: 0,
  },
  {
    id: 20,
    enName: 'rabbit',
    imagePath: './animal_images/rabbit.jpg',
    textPath: './animal_names/rabbit.jpg',
    difficulty: 0,
  },
  {
    id: 21,
    enName: 'alpaca',
    imagePath: './animal_images/alpaca.jpg',
    textPath: './animal_names/alpaca.jpg',
    difficulty: 1,
  },
  {
    id: 22,
    enName: 'bear',
    imagePath: './animal_images/bear.jpg',
    textPath: './animal_names/bear.jpg',
    difficulty: 0,
  },
  {
    id: 23,
    enName: 'bee',
    imagePath: './animal_images/bee.jpg',
    textPath: './animal_names/bee.jpg',
    difficulty: 0,
  },
  {
    id: 24,
    enName: 'beetle',
    imagePath: './animal_images/beetle.jpg',
    textPath: './animal_names/beetle.jpg',
    difficulty: 2,
  },
  {
    id: 25,
    enName: 'bird',
    imagePath: './animal_images/bird.jpg',
    textPath: './animal_names/bird.jpg',
    difficulty: 0,
  },
  {
    id: 26,
    enName: 'caterpillar',
    imagePath: './animal_images/caterpillar.jpg',
    textPath: './animal_names/caterpillar.jpg',
    difficulty: 2,
  },
  {
    id: 27,
    enName: 'rooster',
    imagePath: './animal_images/rooster.jpg',
    textPath: './animal_names/rooster.jpg',
    difficulty: 2,
  },
  {
    id: 28,
    enName: 'cobra',
    imagePath: './animal_images/cobra.jpg',
    textPath: './animal_names/cobra.jpg',
    difficulty: 1,
  },
  {
    id: 29,
    enName: 'crocodile',
    imagePath: './animal_images/crocodile.jpg',
    textPath: './animal_names/crocodile.jpg',
    difficulty: 0,
  },
  {
    id: 30,
    enName: 'dolphin',
    imagePath: './animal_images/dolphin.jpg',
    textPath: './animal_names/dolphin.jpg',
    difficulty: 0,
  },
  {
    id: 31,
    enName: 'eagle',
    imagePath: './animal_images/eagle.jpg',
    textPath: './animal_names/eagle.jpg',
    difficulty: 1,
  },
  {
    id: 32,
    enName: 'goat',
    imagePath: './animal_images/goat.jpg',
    textPath: './animal_names/goat.jpg',
    difficulty: 0,
  },
  {
    id: 33,
    enName: 'hummingbird',
    imagePath: './animal_images/hummingbird.jpg',
    textPath: './animal_names/hummingbird.jpg',
    difficulty: 2,
  },
  {
    id: 34,
    enName: 'leopard',
    imagePath: './animal_images/leopard.jpg',
    textPath: './animal_names/leopard.jpg',
    difficulty: 1,
  },
  {
    id: 35,
    enName: 'lizard',
    imagePath: './animal_images/lizard.jpg',
    textPath: './animal_names/lizard.jpg',
    difficulty: 1,
  },
  {
    id: 36,
    enName: 'monkey',
    imagePath: './animal_images/monkey.jpg',
    textPath: './animal_names/monkey.jpg',
    difficulty: 0,
  },
  {
    id: 37,
    enName: 'shark',
    imagePath: './animal_images/shark.jpg',
    textPath: './animal_names/shark.jpg',
    difficulty: 0,
  },
  {
    id: 38,
    enName: 'shrimp',
    imagePath: './animal_images/shrimp.jpg',
    textPath: './animal_names/shrimp.jpg',
    difficulty: 1,
  },
  {
    id: 39,
    enName: 'snail',
    imagePath: './animal_images/snail.jpg',
    textPath: './animal_names/snail.jpg',
    difficulty: 0,
  },
  {
    id: 40,
    enName: 'turtle',
    imagePath: './animal_images/turtle.jpg',
    textPath: './animal_names/turtle.jpg',
    difficulty: 0,
  },
  {
    id: 41,
    enName: 'wolf',
    imagePath: './animal_images/wolf.jpg',
    textPath: './animal_names/wolf.jpg',
    difficulty: 1,
  },
  {
    id: 42,
    enName: 'anteater',
    imagePath: './animal_images/anteater.jpg',
    textPath: './animal_names/anteater.jpg',
    difficulty: 2,
  },
  {
    id: 43,
    enName: 'armadillo',
    imagePath: './animal_images/armadillo.jpg',
    textPath: './animal_names/armadillo.jpg',
    difficulty: 2,
  },
  {
    id: 44,
    enName: 'baboon',
    imagePath: './animal_images/baboon.jpg',
    textPath: './animal_names/baboon.jpg',
    difficulty: 2,
  },
  {
    id: 45,
    enName: 'beaver',
    imagePath: './animal_images/beaver.jpg',
    textPath: './animal_names/beaver.jpg',
    difficulty: 1,
  },
  {
    id: 46,
    enName: 'bison',
    imagePath: './animal_images/bison.jpg',
    textPath: './animal_names/bison.jpg',
    difficulty: 1,
  },
  {
    id: 47,
    enName: 'boar',
    imagePath: './animal_images/boar.jpg',
    textPath: './animal_names/boar.jpg',
    difficulty: 1,
  },
  {
    id: 48,
    enName: 'camel',
    imagePath: './animal_images/camel.jpg',
    textPath: './animal_names/camel.jpg',
    difficulty: 1,
  },
  {
    id: 49,
    enName: 'cow',
    imagePath: './animal_images/cow.jpg',
    textPath: './animal_names/cow.jpg',
    difficulty: 0,
  },
  {
    id: 50,
    enName: 'crab',
    imagePath: './animal_images/crab.jpg',
    textPath: './animal_names/crab.jpg',
    difficulty: 0,
  },
  {
    id: 51,
    enName: 'donkey',
    imagePath: './animal_images/donkey.jpg',
    textPath: './animal_names/donkey.jpg',
    difficulty: 0,
  },
  {
    id: 52,
    enName: 'duck',
    imagePath: './animal_images/duck.jpg',
    textPath: './animal_names/duck.jpg',
    difficulty: 0,
  },
  {
    id: 53,
    enName: 'flamingo',
    imagePath: './animal_images/flamingo.jpg',
    textPath: './animal_names/flamingo.jpg',
    difficulty: 1,
  },
  {
    id: 54,
    enName: 'goose',
    imagePath: './animal_images/goose.jpg',
    textPath: './animal_names/goose.jpg',
    difficulty: 0,
  },
  {
    id: 55,
    enName: 'gorilla',
    imagePath: './animal_images/gorilla.jpg',
    textPath: './animal_names/gorilla.jpg',
    difficulty: 1,
  },
  {
    id: 56,
    enName: 'guinea pig',
    imagePath: './animal_images/guinea_pig.jpg',
    textPath: './animal_names/guinea_pig.jpg',
    difficulty: 2,
  },
  {
    id: 57,
    enName: 'hippopotamus',
    imagePath: './animal_images/hippopotamus.jpg',
    textPath: './animal_names/hippopotamus.jpg',
    difficulty: 2,
  },
  {
    id: 58,
    enName: 'hyena',
    imagePath: './animal_images/hyena.jpg',
    textPath: './animal_names/hyena.jpg',
    difficulty: 2,
  },
  {
    id: 59,
    enName: 'jackal',
    imagePath: './animal_images/jackal.jpg',
    textPath: './animal_names/jackal.jpg',
    difficulty: 2,
  },
  {
    id: 60,
    enName: 'jaguar',
    imagePath: './animal_images/jaguar.jpg',
    textPath: './animal_names/jaguar.jpg',
    difficulty: 1,
  },
  {
    id: 61,
    enName: 'kangaroo',
    imagePath: './animal_images/kangaroo.jpg',
    textPath: './animal_names/kangaroo.jpg',
    difficulty: 1,
  },
  {
    id: 62,
    enName: 'koala',
    imagePath: './animal_images/koala.jpg',
    textPath: './animal_names/koala.jpg',
    difficulty: 0,
  },
  {
    id: 63,
    enName: 'lemur',
    imagePath: './animal_images/lemur.jpg',
    textPath: './animal_names/lemur.jpg',
    difficulty: 1,
  },
  {
    id: 64,
    enName: 'lobster',
    imagePath: './animal_images/lobster.jpg',
    textPath: './animal_names/lobster.jpg',
    difficulty: 1,
  },
  {
    id: 65,
    enName: 'lynx',
    imagePath: './animal_images/lynx.jpg',
    textPath: './animal_names/lynx.jpg',
    difficulty: 1,
  },
  {
    id: 66,
    enName: 'moose',
    imagePath: './animal_images/moose.jpg',
    textPath: './animal_names/moose.jpg',
    difficulty: 1,
  },
  {
    id: 67,
    enName: 'mouse',
    imagePath: './animal_images/mouse.jpg',
    textPath: './animal_names/mouse.jpg',
    difficulty: 0,
  },
  {
    id: 68,
    enName: 'octopus',
    imagePath: './animal_images/octopus.jpg',
    textPath: './animal_names/octopus.jpg',
    difficulty: 1,
  },
  {
    id: 69,
    enName: 'ostrich',
    imagePath: './animal_images/ostrich.jpg',
    textPath: './animal_names/ostrich.jpg',
    difficulty: 1,
  },
  {
    id: 70,
    enName: 'otter',
    imagePath: './animal_images/otter.jpg',
    textPath: './animal_names/otter.jpg',
    difficulty: 2,
  },
  {
    id: 71,
    enName: 'pig',
    imagePath: './animal_images/pig.jpg',
    textPath: './animal_names/pig.jpg',
    difficulty: 0,
  },
  {
    id: 72,
    enName: 'polar bear',
    imagePath: './animal_images/polar_bear.jpg',
    textPath: './animal_names/polar_bear.jpg',
    difficulty: 2,
  },
  {
    id: 73,
    enName: 'raccoon',
    imagePath: './animal_images/raccoon.jpg',
    textPath: './animal_names/raccoon.jpg',
    difficulty: 1,
  },
  {
    id: 74,
    enName: 'ram',
    imagePath: './animal_images/ram.jpg',
    textPath: './animal_names/ram.jpg',
    difficulty: 1,
  },
  {
    id: 75,
    enName: 'rat',
    imagePath: './animal_images/rat.jpg',
    textPath: './animal_names/rat.jpg',
    difficulty: 0,
  },
  {
    id: 76,
    enName: 'reindeer',
    imagePath: './animal_images/reindeer.jpg',
    textPath: './animal_names/reindeer.jpg',
    difficulty: 2,
  },
  {
    id: 77,
    enName: 'rhinoceros',
    imagePath: './animal_images/rhinoceros.jpg',
    textPath: './animal_names/rhinoceros.jpg',
    difficulty: 2,
  },
  {
    id: 78,
    enName: 'seagull',
    imagePath: './animal_images/seagull.jpg',
    textPath: './animal_names/seagull.jpg',
    difficulty: 2,
  },
  {
    id: 79,
    enName: 'seahorse',
    imagePath: './animal_images/seahorse.jpg',
    textPath: './animal_names/seahorse.jpg',
    difficulty: 2,
  },
  {
    id: 80,
    enName: 'seal',
    imagePath: './animal_images/seal.jpg',
    textPath: './animal_names/seal.jpg',
    difficulty: 1,
  },
  {
    id: 81,
    enName: 'sheep',
    imagePath: './animal_images/sheep.jpg',
    textPath: './animal_names/sheep.jpg',
    difficulty: 0,
  },
  {
    id: 82,
    enName: 'skunk',
    imagePath: './animal_images/skunk.jpg',
    textPath: './animal_names/skunk.jpg',
    difficulty: 1,
  },
  {
    id: 83,
    enName: 'sloth',
    imagePath: './animal_images/sloth.jpg',
    textPath: './animal_names/sloth.jpg',
    difficulty: 1,
  },
  {
    id: 84,
    enName: 'starfish',
    imagePath: './animal_images/starfish.jpg',
    textPath: './animal_names/starfish.jpg',
    difficulty: 2,
  },
  {
    id: 85,
    enName: 'turkey',
    imagePath: './animal_images/turkey.jpg',
    textPath: './animal_names/turkey.jpg',
    difficulty: 0,
  },
  {
    id: 86,
    enName: 'vulture',
    imagePath: './animal_images/vulture.jpg',
    textPath: './animal_names/vulture.jpg',
    difficulty: 2,
  },
  {
    id: 87,
    enName: 'walrus',
    imagePath: './animal_images/walrus.jpg',
    textPath: './animal_names/walrus.jpg',
    difficulty: 2,
  },
  {
    id: 88,
    enName: 'weasel',
    imagePath: './animal_images/weasel.jpg',
    textPath: './animal_names/weasel.jpg',
    difficulty: 2,
  },
  {
    id: 89,
    enName: 'whale',
    imagePath: './animal_images/whale.jpg',
    textPath: './animal_names/whale.jpg',
    difficulty: 1,
  },
  {
    id: 90,
    enName: 'zebra',
    imagePath: './animal_images/zebra.jpg',
    textPath: './animal_names/zebra.jpg',
    difficulty: 0,
  },
  {
    id: 91,
    enName: 'honey badger',
    imagePath: './animal_images/honey_badger.jpg',
    textPath: './animal_names/honey_badger.jpg',
    difficulty: 2,
  },
];

export default animals;
